"""9박 10일 여행일지 콘텐츠. templates/journal.html 이 이 데이터를 렌더링합니다.
Media files live in static/journal/media/."""

DAYS = [{'num': 1,
  'title': '한국에서 프라하로',
  'date': '2026년 7월 27일 월요일',
  'intro': '인천국제공항에서 <b>프라하까지 직항으로 약 13시간</b>을 날아, 갈아탈 필요 없이 하루 만에 도착했습니다. 짐을 풀 새도 없이 노을 지는 구시가지 광장으로 나가 첫 '
           '산책을 했어요.',
  'quote': '“긴 비행 끝에 마주한 도시는, 노을 속에서 우리를 가장 먼저 반겨주었다.”',
  'blocks': [{'type': 'segment',
              'title': '한국에서 출발',
              'time': '오전',
              'gallery': 'd1_s1',
              'gallery_title': '한국에서 출발 · 관련 사진',
              'hero': '/static/journal/media/d192f2ee4b52.jpg',
              'hero_alt': '인천공항',
              'hero_cap': '인천국제공항, 탑승동으로 향하는 길',
              'photos': [{'src': '/static/journal/media/a00ae906db84.jpg',
                          'cap': '기내에서, 설렘 가득',
                          'who': '첫째딸'},
                         {'src': '/static/journal/media/8a0ffe7cc242.jpg', 'cap': '브이 포즈로 한 컷', 'who': '첫째딸'},
                         {'src': '/static/journal/media/98cb60ece38f.jpg', 'cap': '가족 넷이 함께', 'who': None},
                         {'src': '/static/journal/media/9d9a8858e07b.jpg',
                          'cap': '좌석에 나란히 앉아서',
                          'who': None}],
              'note': None,
              'map_label': '인천국제공항',
              'map_q': '37.4671,126.4294',
              'map_zoom': 15},
             {'type': 'segment',
              'title': '구시가지 광장 첫 산책',
              'time': '저녁',
              'gallery': 'd1_s2',
              'gallery_title': '구시가지 광장 · 관련 사진',
              'hero': '/static/journal/media/6c560c6f103e.jpg',
              'hero_alt': '성 미쿨라셰 성당',
              'hero_cap': '구시가지 광장, 성 미쿨라셰 성당 앞',
              'photos': [{'src': '/static/journal/media/efe0eba3ee5d.jpg', 'cap': '노을빛 광장을 걸으며', 'who': None},
                         {'src': '/static/journal/media/805149271922.jpg', 'cap': '성당 앞에서 나란히', 'who': None},
                         {'src': '/static/journal/media/6509b059d687.jpg', 'cap': '광장 카페에서 한 잔', 'who': None},
                         {'src': '/static/journal/media/45ef7fb5d3eb.jpg',
                          'cap': '멀리 보이는 프라하 성',
                          'who': None}],
              'note': None,
              'map_label': '구시가지 광장',
              'map_q': '50.0879,14.4212',
              'map_zoom': 17},
             {'type': 'clip',
              'tag': 'DAY 1 · 5초 영상',
              'src': '/static/journal/media/036805857933.mp4',
              'cap': '천문시계 정각 인형극, 저녁의 구시청사'},
             {'type': 'clip',
              'tag': 'DAY 1 · 5초 영상',
              'src': '/static/journal/media/5ac0b7797922.mp4',
              'cap': '얀 후스 동상과 틴 성모 교회, 구시가지 광장의 저녁'},
             {'type': 'segment',
              'title': '구시청사 인근 & 저녁 식사',
              'time': '밤',
              'gallery': 'd1_s3',
              'gallery_title': '저녁 식사 · 관련 사진',
              'hero': '/static/journal/media/9633c0944c4b.jpg',
              'hero_alt': '큐비즘 박물관 건물',
              'hero_cap': '오보츠니 광장(Ovocný trh), 큐비즘 박물관(검은 성모의 집) 건물',
              'photos': [{'src': '/static/journal/media/f2d14341316c.jpg', 'cap': '테라스에서 첫 건배', 'who': '첫째딸'},
                         {'src': '/static/journal/media/ef0a53362e95.jpg', 'cap': '맥주잔 부딪히며', 'who': None},
                         {'src': '/static/journal/media/7a4ee03b11e8.jpg',
                          'cap': '꽃 장식이 예뻤던 테이블',
                          'who': None},
                         {'src': '/static/journal/media/96ab025d983e.jpg',
                          'cap': '저녁 식사 중 셀카',
                          'who': '둘째딸'}],
              'note': '※ 정확한 레스토랑 이름은 아직 확인 전이에요 — 알려주시면 채워둘게요.',
              'map_label': '오보츠니 광장 (Ovocný trh)',
              'map_q': '50.0868,14.4257',
              'map_zoom': 17}],
  'pill': 'Day 1 · 7.27'},
 {'num': 2,
  'title': '구시가지에서 하루 종일',
  'date': '2026년 7월 28일 화요일',
  'intro': '이른 아침 한산한 골목부터 해가 완전히 저물 때까지, 구시가지와 유대인 지구 구석구석을 걸어 다닌 하루였습니다.',
  'quote': '“가장 좋은 여행은, 지도 없이도 길을 잃지 않는 하루다.”',
  'blocks': [{'type': 'segment',
              'title': '이른 아침 산책',
              'time': '아침',
              'gallery': 'd2_s1',
              'gallery_title': '이른 아침 산책 · 관련 사진',
              'hero': '/static/journal/media/55f3f2b4a5ea.jpg',
              'hero_alt': '천문시계',
              'hero_cap': '구시청사 천문시계(Orloj), 관광객이 없는 이른 시간',
              'photos': [{'src': '/static/journal/media/c9543c8ccd64.jpg',
                          'cap': '아침 햇살 아래, 시계탑 앞에서',
                          'who': '엄마'},
                         {'src': '/static/journal/media/3d16e2de9652.jpg', 'cap': '골목 안쪽 아치문', 'who': '엄마'},
                         {'src': '/static/journal/media/c2c1d84ce760.jpg',
                          'cap': '천문시계 바로 아래에서',
                          'who': '엄마'},
                         {'src': '/static/journal/media/9b3c43484090.jpg', 'cap': '아침 커피 한 잔', 'who': None}],
              'note': None,
              'map_label': '구시청사 천문시계',
              'map_q': '50.0868,14.4208',
              'map_zoom': 18},
             {'type': 'clip',
              'tag': 'DAY 2 · 5초 영상',
              'src': '/static/journal/media/f3d352edb43a.mp4',
              'cap': '이른 아침, 인적 없는 천문시계'},
             {'type': 'clip',
              'tag': 'DAY 2 · 5초 영상',
              'src': '/static/journal/media/9acff0620004.mp4',
              'cap': '숙소 인근에서 내려다본 프라하 지붕 풍경'},
             {'type': 'segment',
              'title': '골목 나들이',
              'time': '낮',
              'gallery': 'd2_s2',
              'gallery_title': '골목 나들이 · 관련 사진',
              'hero': '/static/journal/media/8ef06f05d622.jpg',
              'hero_alt': '아치형 골목길',
              'hero_cap': '구시가지 뒷골목(성 야고보 성당 인근), 아치형 골목길',
              'photos': [{'src': '/static/journal/media/c0fc0838ee59.jpg',
                          'cap': '트램 지나는 거리를 걸으며',
                          'who': None},
                         {'src': '/static/journal/media/a88e3d9972d7.jpg', 'cap': '트램 정류장 앞에서', 'who': None},
                         {'src': '/static/journal/media/c07194194184.jpg', 'cap': '골목을 걷는 가족', 'who': None},
                         {'src': '/static/journal/media/a2322f73b2b1.jpg',
                          'cap': '노란 문이 예뻤던 바(Bar) 앞에서',
                          'who': None}],
              'note': None,
              'map_label': '성 야고보 성당 인근 골목 (Old Town 뒷골목)',
              'map_q': '50.0879,14.4227',
              'map_zoom': 17},
             {'type': 'segment',
              'title': '노을 지는 거리',
              'time': '저녁',
              'gallery': 'd2_s3',
              'gallery_title': '노을 지는 거리 · 관련 사진',
              'hero': '/static/journal/media/9054d367bf07.jpg',
              'hero_alt': '구시가지 코너 건물',
              'hero_cap': '구시가지 초입, 아르누보 양식의 코너 건물',
              'photos': [{'src': '/static/journal/media/2a334254b704.jpg',
                          'cap': '틴 성모 교회를 배경으로',
                          'who': None},
                         {'src': '/static/journal/media/b4ebde5f65df.jpg', 'cap': '노을빛 거리에서', 'who': None},
                         {'src': '/static/journal/media/8a76467c7e04.jpg', 'cap': '구시가지를 걸으며', 'who': None},
                         {'src': '/static/journal/media/e562a7b8c7fd.jpg', 'cap': '코너 건물 앞 거리', 'who': None}],
              'note': None,
              'map_label': '틴 성모 교회 인근',
              'map_q': '50.0879,14.4270',
              'map_zoom': 17}],
  'pill': 'Day 2 · 7.28'},
 {'num': 3,
  'title': '까를교를 건너, 성을 바라보다',
  'date': '2026년 7월 29일 수요일',
  'intro': '구시가지에서 시작해 까를교를 건너 프라하 성을 바라보고, 노천 카페에서 여유를 즐긴 하루였습니다. 트르들로 간식도 빼놓지 않았어요.',
  'quote': '“다리를 건너는 순간, 프라하는 완전히 다른 얼굴을 보여주었다.”',
  'blocks': [{'type': 'segment',
              'title': '구시가지 아침 산책 & 간식',
              'time': '아침~낮',
              'gallery': 'd3_s1',
              'gallery_title': '아침 산책 · 관련 사진',
              'hero': '/static/journal/media/674a7983c7d7.jpg',
              'hero_alt': '구시가지 코너 건물',
              'hero_cap': '구시가지, 이정표가 서 있는 코너 건물',
              'photos': [{'src': '/static/journal/media/2c0a831ea5e4.jpg',
                          'cap': '트램이 지나는 아침 거리',
                          'who': None},
                         {'src': '/static/journal/media/239a0c77ffe7.jpg', 'cap': '광장을 가로지르며', 'who': '아빠'},
                         {'src': '/static/journal/media/869ed2558a15.jpg', 'cap': '아침 산책 중', 'who': None},
                         {'src': '/static/journal/media/241ea0c2fe45.jpg',
                          'cap': '길거리 간식, 트르들로',
                          'who': None}],
              'note': None,
              'map_label': '구시가지 인근',
              'map_q': '50.0895,14.4225',
              'map_zoom': 17},
             {'type': 'clip',
              'tag': 'DAY 3 · 5초 영상',
              'src': '/static/journal/media/87e33dfdf40c.mp4',
              'cap': '구시가지, 아치형 통로를 지나며'},
             {'type': 'segment',
              'title': '까를교, 성을 바라보며',
              'time': '오후',
              'gallery': 'd3_s2',
              'gallery_title': '까를교 · 관련 사진',
              'hero': '/static/journal/media/8b400b6f1e7e.jpg',
              'hero_alt': '구시가 다리탑',
              'hero_cap': '까를교 입구, 구시가 다리탑',
              'photos': [{'src': '/static/journal/media/793a5c8672c5.jpg', 'cap': '다리로 향하는 길', 'who': None},
                         {'src': '/static/journal/media/2bcaaae65f27.jpg',
                          'cap': '다리탑 앞에서 다 함께',
                          'who': None},
                         {'src': '/static/journal/media/da06fc4f5f86.jpg',
                          'cap': '성이 보이는 전망대에서',
                          'who': None},
                         {'src': '/static/journal/media/eccf1209bbd6.jpg',
                          'cap': '까를교에서 바라본 프라하 성',
                          'who': None}],
              'note': None,
              'map_label': '까를교 (Karlův most)',
              'map_q': '50.0862,14.4140',
              'map_zoom': 17},
             {'type': 'clip',
              'tag': 'DAY 3 · 5초 영상',
              'src': '/static/journal/media/4da09f546990.mp4',
              'cap': '점심 무렵 들른 와인 레스토랑'},
             {'type': 'segment',
              'title': '노천 카페 & 쇼핑',
              'time': '저녁',
              'gallery': 'd3_s3',
              'gallery_title': '노천 카페 · 관련 사진',
              'hero': '/static/journal/media/3c9785234367.jpg',
              'hero_alt': '공화국 광장 인근 건물',
              'hero_cap': '공화국 광장 인근, 노을 지는 거리',
              'photos': [{'src': '/static/journal/media/1104b39fe60a.jpg',
                          'cap': '모엣샹동 테라스에서 한 잔',
                          'who': None},
                         {'src': '/static/journal/media/6dd691d66013.jpg', 'cap': '테라스에서 담소를', 'who': None},
                         {'src': '/static/journal/media/3f15452ceae0.jpg', 'cap': '노을 지는 광장 거리', 'who': None},
                         {'src': '/static/journal/media/ce5a376074f0.jpg',
                          'cap': '쇼핑하다 거울 셀카',
                          'who': '첫째딸'}],
              'note': None,
              'map_label': '공화국 광장 인근',
              'map_q': '50.0888,14.4285',
              'map_zoom': 17},
             {'type': 'clip',
              'tag': 'DAY 3 · 5초 영상',
              'src': '/static/journal/media/5bdc19707c5a.mp4',
              'cap': '공화국 광장, 트램이 오가는 저녁 풍경'},
             {'type': 'clip',
              'tag': 'DAY 3 · 영상',
              'src': '/static/journal/media/b7c91e46ffab.mp4',
              'cap': '상점가 골목, 저녁 쇼핑'}],
  'pill': 'Day 3 · 7.29'},
 {'num': 4,
  'title': '수도원, 성, 그리고 야경',
  'date': '2026년 7월 30일 목요일',
  'intro': '아침 베이커리에서 시작해 스트라호프 수도원과 말라스트라나 성당, 그리고 프라하 성과 성 비투스 대성당까지 — 하루 만에 언덕 위아래를 오간 알찬 날이었습니다. 밤에는 존 '
           '레논 벽과 까를교 야경으로 마무리했어요.',
  'quote': '“언덕 위아래를 오가며, 하루가 두 도시만큼 길어졌다.”',
  'blocks': [{'type': 'segment',
              'title': '아침, 베이커리에서 조식',
              'time': '아침',
              'gallery': 'd4_s1',
              'gallery_title': '아침 베이커리 · 관련 사진',
              'hero': '/static/journal/media/2cafd6dd3a24.jpg',
              'hero_alt': '베이커리 진열대',
              'hero_cap': '구시가지 인근 베이커리, 형형색색의 페이스트리',
              'photos': [{'src': '/static/journal/media/87be2ed41f13.jpg',
                          'cap': '골목 벤치에서 잠시 휴식',
                          'who': None},
                         {'src': '/static/journal/media/38181a14c2ec.jpg', 'cap': '아침 거리를 걸으며', 'who': None},
                         {'src': '/static/journal/media/5361c1de38c3.jpg',
                          'cap': '커피 들고 셀카',
                          'who': '아빠 · 첫째딸'},
                         {'src': '/static/journal/media/f099a5696227.jpg',
                          'cap': '테이크아웃 커피와 아침 산책',
                          'who': None}],
              'note': None,
              'map_label': '구시가지 인근 베이커리',
              'map_q': '50.0905,14.4278',
              'map_zoom': 17},
             {'type': 'segment',
              'title': '스트라호프 수도원 & 점심',
              'time': '낮',
              'gallery': 'd4_s2',
              'gallery_title': '스트라호프 수도원 · 관련 사진',
              'hero': '/static/journal/media/f2d040856558.jpg',
              'hero_alt': '스트라호프 수도원 성당 내부',
              'hero_cap': '스트라호프 수도원 성당, 어두운 목조와 금장 장식이 인상적인 내부',
              'photos': [{'src': '/static/journal/media/ac0adec4ae9d.jpg', 'cap': '안내 책자 들고 브이', 'who': '엄마'},
                         {'src': '/static/journal/media/05fa8ed9f2bc.jpg', 'cap': '든든한 점심 한 상', 'who': None},
                         {'src': '/static/journal/media/427530950a8e.jpg',
                          'cap': '말라스트라나 성 미쿨라셰 성당, 화려한 금장 내부',
                          'who': None},
                         {'src': '/static/journal/media/7f2083904318.jpg', 'cap': '언덕길을 걸으며', 'who': None}],
              'note': '※ 점심 레스토랑 이름은 아직 확인 전이에요 — 알려주시면 채워둘게요.',
              'map_label': '스트라호프 수도원',
              'map_q': '50.0864,14.3890',
              'map_zoom': 16},
             {'type': 'clip',
              'tag': 'DAY 4 · 5초 영상',
              'src': '/static/journal/media/5e30c547a071.mp4',
              'cap': '스트라호프 수도원, 프레스코 천장화'},
             {'type': 'clip',
              'tag': 'DAY 4 · 5초 영상',
              'src': '/static/journal/media/be1f132309e6.mp4',
              'cap': '블타바 강변의 뉴트리아와 오리들'},
             {'type': 'segment',
              'title': '프라하 성 & 성 비투스 대성당',
              'time': '저녁',
              'gallery': 'd4_s3',
              'gallery_title': '프라하 성 · 관련 사진',
              'hero': '/static/journal/media/08d1b57d8daf.jpg',
              'hero_alt': '성 비투스 대성당',
              'hero_cap': '프라하 성 단지 내, 성 비투스 대성당',
              'photos': [{'src': '/static/journal/media/0838c67a5b56.jpg',
                          'cap': '대성당 앞에서 다 함께',
                          'who': None},
                         {'src': '/static/journal/media/bb2906765f87.jpg', 'cap': '성벽에서 바라본 노을', 'who': None},
                         {'src': '/static/journal/media/8c320c372126.jpg', 'cap': '성 모형 전시 구경', 'who': '첫째딸'},
                         {'src': '/static/journal/media/de93a9815dab.jpg',
                          'cap': '기념품 가게에서',
                          'who': '아빠 · 엄마 · 둘째딸'}],
              'note': None,
              'map_label': '프라하 성 (성 비투스 대성당)',
              'map_q': '50.0905,14.3998',
              'map_zoom': 16},
             {'type': 'segment',
              'title': '존 레논 벽 & 까를교 야경',
              'time': '밤',
              'gallery': 'd4_s4',
              'gallery_title': '까를교 야경 · 관련 사진',
              'hero': '/static/journal/media/cc00806b24ed.jpg',
              'hero_alt': '구시가 다리탑 야경',
              'hero_cap': '까를교, 조명이 켜진 구시가 다리탑',
              'photos': [{'src': '/static/journal/media/a9bb868668a3.jpg', 'cap': '존 레논 벽 앞에서', 'who': None},
                         {'src': '/static/journal/media/69c8b21737f5.jpg',
                          'cap': '야경 속 프라하 성 조망',
                          'who': None},
                         {'src': '/static/journal/media/c6c04acb34eb.jpg', 'cap': '야간 거리 산책', 'who': None},
                         {'src': '/static/journal/media/e6c028c89957.jpg', 'cap': '트램 지나는 밤거리', 'who': None}],
              'note': None,
              'map_label': '까를교 (Karlův most)',
              'map_q': '50.0862,14.4132',
              'map_zoom': 16}],
  'pill': 'Day 4 · 7.30'},
 {'num': 5,
  'title': '성 안 깊숙이, 그리고 강 위에서',
  'date': '2026년 7월 31일 금요일',
  'intro': '이번엔 성 비투스 대성당 내부와 골든 레인, 왕실 정원까지 프라하 성 구석구석을 둘러봤어요. 저녁엔 까를교 노을을 보고, 밤에는 블타바 강 야간 크루즈로 하루를 '
           '마무리했습니다.',
  'quote': '“강 위에서 바라본 성은, 낮과는 다른 표정을 하고 있었다.”',
  'blocks': [{'type': 'clip',
              'tag': 'DAY 5 · 5초 영상',
              'src': '/static/journal/media/e3cf0c2ec6f7.mp4',
              'cap': '이른 아침, 조용한 프라하 골목'},
             {'type': 'segment',
              'title': '성 비투스 대성당 내부 & 골든 레인, 왕실 정원',
              'time': '오전~낮',
              'gallery': 'd5_s1',
              'gallery_title': '성 내부 · 관련 사진',
              'hero': '/static/journal/media/1c55426717eb.jpg',
              'hero_alt': '성 비투스 대성당 스테인드글라스',
              'hero_cap': '성 비투스 대성당 내부, 화려한 스테인드글라스 창',
              'photos': [{'src': '/static/journal/media/b4f30481b4a3.jpg',
                          'cap': '대성당 안, 황금빛 모자이크 앞에서',
                          'who': None},
                         {'src': '/static/journal/media/f4d04292dc35.jpg',
                          'cap': '골든 레인의 작은 집들',
                          'who': None},
                         {'src': '/static/journal/media/721b6379ff70.jpg', 'cap': '골든 레인 실내 통로', 'who': None},
                         {'src': '/static/journal/media/cbe2c90bd697.jpg', 'cap': '왕실 정원을 거닐며', 'who': None}],
              'note': None,
              'map_label': '프라하 성 (성 비투스 대성당)',
              'map_q': '50.0910,14.3999',
              'map_zoom': 16},
             {'type': 'clip',
              'tag': 'DAY 5 · 5초 영상',
              'src': '/static/journal/media/6df2b5d407da.mp4',
              'cap': '성 비투스 대성당, 스테인드글라스와 제단'},
             {'type': 'clip',
              'tag': 'DAY 5 · 5초 영상',
              'src': '/static/journal/media/26ac5f5ac353.mp4',
              'cap': '성 조지 성당, 프레스코 천장이 아름다운 내부'},
             {'type': 'segment',
              'title': '까를교 노을 & 카페 휴식',
              'time': '늦은 오후',
              'gallery': 'd5_s2',
              'gallery_title': '까를교 노을 · 관련 사진',
              'hero': '/static/journal/media/fd0a54722c8b.jpg',
              'hero_alt': '까를교와 블타바 강변',
              'hero_cap': '블타바 강변에서 바라본 까를교',
              'photos': [{'src': '/static/journal/media/80c10c6abc92.jpg',
                          'cap': '이동하는 길, 창밖 풍경',
                          'who': None},
                         {'src': '/static/journal/media/0b11d85325d3.jpg', 'cap': '정류장에서 잠시 대기', 'who': None},
                         {'src': '/static/journal/media/a9b1e5192ebc.jpg',
                          'cap': '성당 앞 거리 공연 안내',
                          'who': None},
                         {'src': '/static/journal/media/c311eb75a01c.jpg',
                          'cap': '카페에서 달콤한 휴식',
                          'who': None}],
              'note': '※ 정확한 이동 경로와 카페 이름은 아직 확인 전이에요 — 알려주시면 채워둘게요.',
              'map_label': '까를교 인근',
              'map_q': '50.0865,14.4114',
              'map_zoom': 16},
             {'type': 'segment',
              'title': '블타바 강 야간 크루즈 & 까를교 야경',
              'time': '밤',
              'gallery': 'd5_s3',
              'gallery_title': '야간 크루즈 · 관련 사진',
              'hero': '/static/journal/media/6e9db9a94e7a.jpg',
              'hero_alt': '야간 크루즈에서 본 프라하 성',
              'hero_cap': '블타바 강 야간 크루즈에서 바라본 조명 켜진 프라하 성',
              'photos': [{'src': '/static/journal/media/a2288254f50f.jpg',
                          'cap': '까를교에서, 성을 배경으로',
                          'who': None},
                         {'src': '/static/journal/media/244da62a646c.jpg',
                          'cap': '멀리서 바라본 성의 야경',
                          'who': None},
                         {'src': '/static/journal/media/564539409006.jpg',
                          'cap': '강변을 따라 반짝이는 불빛',
                          'who': None},
                         {'src': '/static/journal/media/1f4ad38393c1.jpg',
                          'cap': '조명이 켜진 구시가 다리탑',
                          'who': None}],
              'note': None,
              'map_label': '블타바 강, 까를교 인근',
              'map_q': '50.0865,14.4109',
              'map_zoom': 16}],
  'pill': 'Day 5 · 7.31'},
 {'num': 6,
  'title': '국경을 넘어, 드레스덴',
  'date': '2026년 8월 1일 토요일',
  'intro': '이날은 프라하를 벗어나 독일 드레스덴으로 당일치기 여행을 다녀왔어요. 프라우엔 교회와 츠빙거 궁전, 엘베강변을 둘러보고 저녁엔 다시 프라하로 돌아와 하루를 마무리했습니다.',
  'quote': '“국경 하나를 넘었을 뿐인데, 전혀 다른 나라의 리듬이 기다리고 있었다.”',
  'blocks': [{'type': 'segment',
              'title': '드레스덴 도착 & 프라우엔 교회',
              'time': '오전~낮',
              'gallery': 'd6_s1',
              'gallery_title': '프라우엔 교회 · 관련 사진',
              'hero': '/static/journal/media/86ec33b3c640.jpg',
              'hero_alt': '프라우엔 교회',
              'hero_cap': '드레스덴 프라우엔 교회(Frauenkirche)',
              'photos': [{'src': '/static/journal/media/358d93676945.jpg',
                          'cap': '드레스덴 중앙역에 도착',
                          'who': None},
                         {'src': '/static/journal/media/b44ea164a0b3.jpg',
                          'cap': '구시가지를 지나는 마차',
                          'who': None},
                         {'src': '/static/journal/media/891df1ec7709.jpg',
                          'cap': '프라우엔 교회 앞에서',
                          'who': '엄마, 첫째딸, 둘째딸'},
                         {'src': '/static/journal/media/42da8fb61cb0.jpg',
                          'cap': '현지 레스토랑에서 점심',
                          'who': '아빠'}],
              'note': '※ 점심 레스토랑 이름은 아직 확인 전이에요 — 알려주시면 채워둘게요.',
              'map_label': '드레스덴, 프라우엔 교회',
              'map_q': '51.0516,13.7427',
              'map_zoom': 16},
             {'type': 'segment',
              'title': '츠빙거 궁전 & 엘베강변',
              'time': '오후',
              'gallery': 'd6_s2',
              'gallery_title': '츠빙거 궁전 · 관련 사진',
              'hero': '/static/journal/media/392cae011196.jpg',
              'hero_alt': '츠빙거 궁전',
              'hero_cap': '츠빙거 궁전(Zwinger) 입구',
              'photos': [{'src': '/static/journal/media/1288cef6db0e.jpg',
                          'cap': '궁전 앞에서 다 함께',
                          'who': '엄마, 첫째딸, 둘째딸'},
                         {'src': '/static/journal/media/6e954c26d885.jpg',
                          'cap': '엘베강변, 네 가족 완전체 셀카',
                          'who': None},
                         {'src': '/static/journal/media/5fabcc62918e.jpg', 'cap': '강변을 따라 산책', 'who': None},
                         {'src': '/static/journal/media/e7d615c32abd.jpg',
                          'cap': '구시가지 지도 표지판에서',
                          'who': None}],
              'note': None,
              'map_label': '츠빙거 궁전',
              'map_q': '51.0531,13.7369',
              'map_zoom': 16},
             {'type': 'clip',
              'tag': 'DAY 6 · 짧은 영상',
              'src': '/static/journal/media/484d2db06178.mp4',
              'cap': '성 미쿨라셰 성당 야경 앞에서'},
             {'type': 'segment',
              'title': '프라하로 복귀, 밤 산책',
              'time': '밤',
              'gallery': 'd6_s3',
              'gallery_title': '말라스트라나 야경 · 관련 사진',
              'hero': '/static/journal/media/9ab309095e7c.jpg',
              'hero_alt': '성 미쿨라셰 성당 야경',
              'hero_cap': '말라스트라나 광장, 성 미쿨라셰 성당 야경',
              'photos': [{'src': '/static/journal/media/8dd107e9ec06.jpg',
                          'cap': '피자 가게가 늘어선 저녁 거리',
                          'who': None},
                         {'src': '/static/journal/media/16bb336ff0d4.jpg', 'cap': '샤브샤브로 저녁 식사', 'who': None},
                         {'src': '/static/journal/media/9afa305cd9ad.jpg', 'cap': '야경 속 성당 앞에서', 'who': None},
                         {'src': '/static/journal/media/be06f31eb7cd.jpg',
                          'cap': '불 켜진 밤거리를 걸으며',
                          'who': None}],
              'note': '※ 저녁 식사 레스토랑 이름은 아직 확인 전이에요 — 알려주시면 채워둘게요.',
              'map_label': '말라스트라나 광장',
              'map_q': '50.0877,14.4050',
              'map_zoom': 17}],
  'pill': 'Day 6 · 8.1'},
 {'num': 7,
  'title': '동화 속 마을, 체스키 크룸로프',
  'date': '2026년 8월 2일 일요일',
  'intro': '이번엔 남쪽으로 내려가 체스키 크룸로프로 당일치기를 다녀왔어요. 언덕 위 성에서 내려다본 구시가지, 굽이치는 블타바 강, 노을 속 저녁 산책까지 — 프라하와는 또 다른 '
           '매력의 하루였습니다.',
  'quote': '“동화는 가끔, 실제로 존재하는 마을의 얼굴을 하고 있다.”',
  'blocks': [{'type': 'segment',
              'title': '체스키 크룸로프 성',
              'time': '낮',
              'gallery': 'd7_s1',
              'gallery_title': '체스키 크룸로프 성 · 관련 사진',
              'hero': '/static/journal/media/9865ecfaa290.jpg',
              'hero_alt': '체스키 크룸로프 성에서 본 구시가지',
              'hero_cap': '체스키 크룸로프 성에서 내려다본 구시가지',
              'photos': [{'src': '/static/journal/media/5423b5ead0c4.jpg',
                          'cap': '성 외벽 앞에서 다 함께',
                          'who': None},
                         {'src': '/static/journal/media/ca30384780eb.jpg', 'cap': '성 안뜰을 거닐며', 'who': None},
                         {'src': '/static/journal/media/8e9d29c82c4d.jpg', 'cap': '꽃으로 장식된 회랑', 'who': None},
                         {'src': '/static/journal/media/5731885dbd56.jpg', 'cap': '강변 마을 풍경', 'who': None}],
              'note': None,
              'map_label': '체스키 크룸로프 성',
              'map_q': '48.8123,14.3134',
              'map_zoom': 16},
             {'type': 'segment',
              'title': '구시가지 골목 & 전망',
              'time': '오후',
              'gallery': 'd7_s2',
              'gallery_title': '구시가지 전망 · 관련 사진',
              'hero': '/static/journal/media/abf21fbfb510.jpg',
              'hero_alt': '체스키 크룸로프 전망',
              'hero_cap': '언덕 위 전망대에서 바라본 마을 전경',
              'photos': [{'src': '/static/journal/media/d1e4e88fd833.jpg',
                          'cap': '나무 그늘 아래 광장에서',
                          'who': None},
                         {'src': '/static/journal/media/7e7dd7657e20.jpg', 'cap': '작은 성당 앞에서', 'who': None},
                         {'src': '/static/journal/media/9a3735916026.jpg',
                          'cap': '기념품 골목을 구경하며',
                          'who': None},
                         {'src': '/static/journal/media/636d670f704e.jpg',
                          'cap': '구시가지 광장을 배경으로',
                          'who': None}],
              'note': None,
              'map_label': '체스키 크룸로프 구시가지',
              'map_q': '48.8122,14.3124',
              'map_zoom': 16},
             {'type': 'clip',
              'tag': 'DAY 7 · 5초 영상',
              'src': '/static/journal/media/135bb79075fc.mp4',
              'cap': '성벽 위에서 내려다본 구시가지 지붕들'},
             {'type': 'segment',
              'title': '블타바 강변 노을 & 저녁',
              'time': '저녁~밤',
              'gallery': 'd7_s3',
              'gallery_title': '강변 노을 · 관련 사진',
              'hero': '/static/journal/media/2f2435c20337.jpg',
              'hero_alt': '노을 속 체스키 크룸로프 성 탑',
              'hero_cap': '블타바 강변에서 바라본 노을 속 성 탑',
              'photos': [{'src': '/static/journal/media/03b14f2804b6.jpg', 'cap': '노을빛 골목을 걸으며', 'who': None},
                         {'src': '/static/journal/media/a3cb16256cae.jpg',
                          'cap': '성 비투스 성당 계단에서',
                          'who': None},
                         {'src': '/static/journal/media/56650c30f738.jpg', 'cap': '저녁 식사 자리에서', 'who': None},
                         {'src': '/static/journal/media/793c702f15a8.jpg', 'cap': '불 켜진 저녁 거리', 'who': None}],
              'note': '※ 저녁 식사 레스토랑 이름은 아직 확인 전이에요 — 알려주시면 채워둘게요.',
              'map_label': '체스키 크룸로프, 블타바 강변',
              'map_q': '48.8121,14.3136',
              'map_zoom': 16},
             {'type': 'clip',
              'tag': 'DAY 7 · 5초 영상',
              'src': '/static/journal/media/bb6594dfeaaa.mp4',
              'cap': '성벽에서 바라본 노을 지는 구시가지'}],
  'pill': 'Day 7 · 8.2'},
 {'num': 8,
  'title': '백조의 성, 그리고 새 동네',
  'date': '2026년 8월 3일 월요일',
  'intro': '체스키 크룸로프에서의 마지막 아침을 보내고, 돌아오는 길에 하얀 외벽이 인상적인 흘루보카 성에 들렀어요. 저녁엔 프라하의 새 숙소로 옮겨 비노흐라디 동네를 산책했습니다.',
  'quote': '“여행의 절반을 넘기고 나서야, 이 도시가 조금씩 편해지기 시작했다.”',
  'blocks': [{'type': 'segment',
              'title': '체스키 크룸로프 마지막 아침',
              'time': '아침~낮',
              'gallery': 'd8_s1',
              'gallery_title': '크룸로프 아침 · 관련 사진',
              'hero': '/static/journal/media/eee52b840ec6.jpg',
              'hero_alt': '체스키 크룸로프 뷰포인트',
              'hero_cap': '강 건너에서 바라본 체스키 크룸로프 성',
              'photos': [{'src': '/static/journal/media/511a6f28a91d.jpg', 'cap': '성벽 터널을 지나며', 'who': None},
                         {'src': '/static/journal/media/c8687a1a62c9.jpg', 'cap': '골목 벤치에서 잠시', 'who': None},
                         {'src': '/static/journal/media/b424c3cb76b7.jpg', 'cap': '뷰포인트에서 다 함께', 'who': None},
                         {'src': '/static/journal/media/4709780eb164.jpg',
                          'cap': '성벽 앞에서 마지막 인증샷',
                          'who': '엄마'}],
              'note': None,
              'map_label': '체스키 크룸로프',
              'map_q': '48.8097,14.3184',
              'map_zoom': 15},
             {'type': 'clip',
              'tag': 'DAY 8 · 5초 영상',
              'src': '/static/journal/media/0b62795b1ffd.mp4',
              'cap': '흘루보카 성, 사냥 트로피가 걸린 복도'},
             {'type': 'segment',
              'title': '흘루보카 성',
              'time': '오후',
              'gallery': 'd8_s2',
              'gallery_title': '흘루보카 성 · 관련 사진',
              'hero': '/static/journal/media/4f9cba62725d.jpg',
              'hero_alt': '흘루보카 성 외벽',
              'hero_cap': '흘루보카 성(백조의 성), 하얀 네오고딕 외벽',
              'photos': [{'src': '/static/journal/media/5ac73fd3fd72.jpg', 'cap': '사냥 트로피 전시실', 'who': None},
                         {'src': '/static/journal/media/135536d4f6d1.jpg', 'cap': '스테인드글라스 계단창', 'who': None},
                         {'src': '/static/journal/media/70bad251b0d0.jpg', 'cap': '성 정원을 거닐며', 'who': None},
                         {'src': '/static/journal/media/809ce87a475e.jpg', 'cap': '성 전체 전경', 'who': None}],
              'note': '※ 프라하와 체스키 크룸로프 사이, 남보헤미아에 위치한 성이에요.',
              'map_label': '흘루보카 성',
              'map_q': '49.0513,14.4415',
              'map_zoom': 16},
             {'type': 'segment',
              'title': '프라하 새 숙소 & 비노흐라디 저녁 산책',
              'time': '저녁~밤',
              'gallery': 'd8_s3',
              'gallery_title': '새 숙소 인근 · 관련 사진',
              'hero': '/static/journal/media/fb3e272d16ab.jpg',
              'hero_alt': '새 숙소 건물 입구',
              'hero_cap': '비노흐라디, 샹들리에와 스테인드글라스 문이 있는 새 숙소 입구',
              'photos': [{'src': '/static/journal/media/e3d84cd0122c.jpg', 'cap': '새 숙소 거실', 'who': None},
                         {'src': '/static/journal/media/033b0219f2da.jpg', 'cap': '숙소 건물 외관', 'who': None},
                         {'src': '/static/journal/media/a0b44038f7fc.jpg', 'cap': '야간 시내 산책', 'who': None},
                         {'src': '/static/journal/media/afba2467e98c.jpg',
                          'cap': '공원에서 바라본 야경',
                          'who': None}],
              'note': '※ 프라하 후반부는 비노흐라디 지역에서 묵는 것 같아요 — 숙소 이름을 알려주시면 채워둘게요.',
              'map_label': '비노흐라디',
              'map_q': '50.0805,14.4370',
              'map_zoom': 16}],
  'pill': 'Day 8 · 8.3'},
 {'num': 9,
  'title': '박물관, 그리고 노을 한 잔',
  'date': '2026년 8월 4일 화요일',
  'intro': '낮에는 국립 박물관의 화려한 내부를 둘러보고, 저녁엔 리흐로비 공원에 자리를 잡고 앉아 프라하의 노을을 오래 바라봤어요. 여행이 얼마 남지 않았다는 게 실감 나는 '
           '하루였습니다.',
  'quote': '“떠날 날이 다가올수록, 노을은 더 오래 바라보게 된다.”',
  'blocks': [{'type': 'clip',
              'tag': 'DAY 9 · 5초 영상',
              'src': '/static/journal/media/c26cacf306f7.mp4',
              'cap': '아침, 창밖으로 보이는 프라하 중앙역'},
             {'type': 'segment',
              'title': '국립 박물관',
              'time': '오후',
              'gallery': 'd9_s1',
              'gallery_title': '국립 박물관 · 관련 사진',
              'hero': '/static/journal/media/5219f6296d10.jpg',
              'hero_alt': '국립 박물관 유리돔 아트리움',
              'hero_cap': '국립 박물관, 화려한 유리돔 아트리움',
              'photos': [{'src': '/static/journal/media/5660de1d9158.jpg', 'cap': '박물관 외벽 계단에서', 'who': None},
                         {'src': '/static/journal/media/1bc9a29ce85c.jpg', 'cap': '화려한 아치형 로비', 'who': None},
                         {'src': '/static/journal/media/601d992a42b1.jpg', 'cap': '기둥 사이를 걸으며', 'who': None},
                         {'src': '/static/journal/media/e33542ad7687.jpg',
                          'cap': '전시실에서 잠시 목을 축이며',
                          'who': None}],
              'note': None,
              'map_label': '국립 박물관',
              'map_q': '50.0789,14.4310',
              'map_zoom': 16},
             {'type': 'clip',
              'tag': 'DAY 9 · 5초 영상',
              'src': '/static/journal/media/a5cc20d14967.mp4',
              'cap': '국립 박물관, 화려한 돔 천장화'},
             {'type': 'clip',
              'tag': 'DAY 9 · 5초 영상',
              'src': '/static/journal/media/d8be884d950d.mp4',
              'cap': '리흐로비 공원, 노을을 보러 모인 사람들'},
             {'type': 'segment',
              'title': '리흐로비 공원 노을',
              'time': '저녁',
              'gallery': 'd9_s2',
              'gallery_title': '리흐로비 공원 노을 · 관련 사진',
              'hero': '/static/journal/media/42769f5452c1.jpg',
              'hero_alt': '리흐로비 공원에서 본 노을과 프라하 스카이라인',
              'hero_cap': '리흐로비 공원(Riegrovy sady), 프라하 성까지 보이는 노을 파노라마',
              'photos': [{'src': '/static/journal/media/516636e94bc2.jpg', 'cap': '잔디밭에 자리 잡고', 'who': None},
                         {'src': '/static/journal/media/636a1bc86037.jpg', 'cap': '노을을 바라보며', 'who': None},
                         {'src': '/static/journal/media/c9d485549c18.jpg',
                          'cap': '함께 앉아 하루를 마무리',
                          'who': None},
                         {'src': '/static/journal/media/8125aa903632.jpg',
                          'cap': '멀리 보이는 프라하 성 실루엣',
                          'who': None}],
              'note': None,
              'map_label': '리흐로비 공원',
              'map_q': '50.0798,14.4401',
              'map_zoom': 16}],
  'pill': 'Day 9 · 8.4'},
 {'num': 10,
  'title': '안녕, 프라하',
  'date': '2026년 8월 5일 수요일',
  'intro': '9박 10일의 마지막 날. 비노흐라디에서 여유로운 아침과 마지막 한 끼를 즐기고, 공항으로 향했습니다. 여권과 탑승권을 손에 쥔 순간부터, 비행기 창밖으로 프라하가 멀어지는 '
           '순간까지 — 이 여행의 마지막 장면들이에요.',
  'quote': '“떠나는 자리에서 돌아보면, 여행은 언제나 조금 더 길게 남는다.”',
  'blocks': [{'type': 'segment',
              'title': '비노흐라디 마지막 아침 & 점심',
              'time': '오전~낮',
              'gallery': 'd10_s1',
              'gallery_title': '비노흐라디 마지막 날 · 관련 사진',
              'hero': '/static/journal/media/43b5f3759ceb.jpg',
              'hero_alt': '비노흐라디 거리',
              'hero_cap': '비노흐라디, 나무 그늘이 드리운 거리',
              'photos': [{'src': '/static/journal/media/cacfb2fec44d.jpg',
                          'cap': '"LA VIE" 레스토랑 입구에서',
                          'who': None},
                         {'src': '/static/journal/media/23f31862a9c0.jpg', 'cap': '알록달록한 카페에서', 'who': None},
                         {'src': '/static/journal/media/0b8ccb20895e.jpg', 'cap': '창가 자리에서 담소를', 'who': '아빠'},
                         {'src': '/static/journal/media/833e58ecc0f5.jpg',
                          'cap': '프라하에서의 마지막 만찬',
                          'who': '아빠'}],
              'note': '※ 레스토랑·카페 정확한 이름은 아직 확인 전이에요 — 알려주시면 채워둘게요.',
              'map_label': '비노흐라디',
              'map_q': '50.0789,14.4362',
              'map_zoom': 16},
             {'type': 'segment',
              'title': '공항으로, 그리고 마지막 하늘',
              'time': '오후~저녁',
              'gallery': 'd10_s2',
              'gallery_title': '공항 · 관련 사진',
              'hero': '/static/journal/media/ab3a59ad5f25.jpg',
              'hero_alt': '여권과 탑승권',
              'hero_cap': '가족 네 명의 여권과 탑승권, 출국 전 마지막 확인',
              'photos': [{'src': '/static/journal/media/2999ec4fba0e.jpg',
                          'cap': '공항에서의 마지막 한 끼',
                          'who': None},
                         {'src': '/static/journal/media/b7c215f89f0f.jpg', 'cap': '탑승 전 셀카', 'who': None},
                         {'src': '/static/journal/media/c73cd8e519a9.jpg', 'cap': '게이트에서 대기하며', 'who': '둘째딸'},
                         {'src': '/static/journal/media/0961b3678780.jpg', 'cap': '마지막까지 함께', 'who': None}],
              'note': None,
              'map_label': '프라하 바츨라프 하벨 공항',
              'map_q': '50.1009,14.2685',
              'map_zoom': 14}],
  'pill': 'Day 10 · 8.5'}]

TRIP_END = {'img': '/static/journal/media/06fd8042ba29.jpg',
 'alt': '비행기 창밖으로 보이는 활주로와 구름',
 'eyebrow': '2026.07.27 → 2026.08.05',
 'title': '9박 10일, 안녕히',
 'text': '인천에서 시작해 프라하 구석구석과 드레스덴, 체스키 크룸로프, 흘루보카까지 — 아빠, 엄마, 첫째딸, 둘째딸 넷이 함께 채운 열흘이었습니다.<br>비행기 창밖으로 활주로가 '
         '멀어지는 이 장면을 마지막으로, 여행 일지를 마칩니다.'}

ALBUM_TABS = [('all', '전체'),
 ('oldtown_sq', '구시가지 광장'),
 ('republic_sq', '공화국 광장'),
 ('castle', '프라하 성'),
 ('strahov', '스트라호프 수도원'),
 ('charles_bridge', '까를교'),
 ('riverside', '블타바 강변'),
 ('mala_strana', '말라스트라나'),
 ('dresden', '드레스덴'),
 ('krumlov', '체스키 크룸로프'),
 ('hluboka', '흘루보카 성'),
 ('vinohrady', '비노흐라디'),
 ('museum', '국립 박물관'),
 ('riegrovy', '리흐로비 공원'),
 ('airport', '공항')]

ALBUM = [{'place': 'oldtown_sq', 'src': '/static/journal/media/c3129fdd41ee.jpg', 'cap': 'Day1 · 구시가지 광장'},
 {'place': 'oldtown_sq', 'src': '/static/journal/media/337cc2171bc7.jpg', 'cap': 'Day1 · 구시가지 광장'},
 {'place': 'oldtown_sq', 'src': '/static/journal/media/fe99b010f5a7.jpg', 'cap': 'Day1 · 구시가지 광장'},
 {'place': 'oldtown_sq', 'src': '/static/journal/media/7a4718feaa11.jpg', 'cap': 'Day2 · 구시가지 광장'},
 {'place': 'oldtown_sq', 'src': '/static/journal/media/0d9387d51c30.jpg', 'cap': 'Day2 · 구시가지 광장'},
 {'place': 'republic_sq', 'src': '/static/journal/media/1e46c66682b3.jpg', 'cap': 'Day1 · 공화국 광장'},
 {'place': 'republic_sq', 'src': '/static/journal/media/cab955ad1b4b.jpg', 'cap': 'Day1 · 공화국 광장'},
 {'place': 'republic_sq', 'src': '/static/journal/media/4f112a72a747.jpg', 'cap': 'Day2 · 공화국 광장'},
 {'place': 'republic_sq', 'src': '/static/journal/media/77031a9662b5.jpg', 'cap': 'Day3 · 공화국 광장'},
 {'place': 'republic_sq', 'src': '/static/journal/media/97228ce6f522.jpg', 'cap': 'Day3 · 공화국 광장'},
 {'place': 'castle', 'src': '/static/journal/media/ca63586a4542.jpg', 'cap': 'Day4 · 프라하 성'},
 {'place': 'castle', 'src': '/static/journal/media/3a851023864b.jpg', 'cap': 'Day4 · 프라하 성'},
 {'place': 'castle', 'src': '/static/journal/media/de38d74eb9f5.jpg', 'cap': 'Day4 · 프라하 성'},
 {'place': 'castle', 'src': '/static/journal/media/e91b595185d9.jpg', 'cap': 'Day5 · 프라하 성'},
 {'place': 'castle', 'src': '/static/journal/media/8f14993dda95.jpg', 'cap': 'Day5 · 프라하 성'},
 {'place': 'strahov', 'src': '/static/journal/media/bd8ad24c242e.jpg', 'cap': 'Day4 · 스트라호프 수도원'},
 {'place': 'strahov', 'src': '/static/journal/media/8fd6c4cc8758.jpg', 'cap': 'Day4 · 스트라호프 수도원'},
 {'place': 'strahov', 'src': '/static/journal/media/fbca35d49c96.jpg', 'cap': 'Day4 · 스트라호프 수도원'},
 {'place': 'strahov', 'src': '/static/journal/media/81e8ff1ab74e.jpg', 'cap': 'Day4 · 스트라호프 수도원'},
 {'place': 'strahov', 'src': '/static/journal/media/606116db5148.jpg', 'cap': 'Day4 · 스트라호프 수도원'},
 {'place': 'charles_bridge', 'src': '/static/journal/media/efbf9c95481e.jpg', 'cap': 'Day3 · 까를교'},
 {'place': 'charles_bridge', 'src': '/static/journal/media/9b364cf88ad2.jpg', 'cap': 'Day3 · 까를교'},
 {'place': 'charles_bridge', 'src': '/static/journal/media/271056c1ebec.jpg', 'cap': 'Day3 · 까를교'},
 {'place': 'charles_bridge', 'src': '/static/journal/media/51f0a22aceda.jpg', 'cap': 'Day3 · 까를교'},
 {'place': 'charles_bridge', 'src': '/static/journal/media/4328eb616a61.jpg', 'cap': 'Day5 · 까를교'},
 {'place': 'riverside', 'src': '/static/journal/media/770a6dfd8c83.jpg', 'cap': 'Day3 · 블타바 강변'},
 {'place': 'riverside', 'src': '/static/journal/media/8f856b65d261.jpg', 'cap': 'Day4 · 블타바 강변'},
 {'place': 'riverside', 'src': '/static/journal/media/344c4982148d.jpg', 'cap': 'Day4 · 블타바 강변'},
 {'place': 'riverside', 'src': '/static/journal/media/ba4621918d75.jpg', 'cap': 'Day5 · 블타바 강변'},
 {'place': 'riverside', 'src': '/static/journal/media/bf97a0d4d263.jpg', 'cap': 'Day6 · 블타바 강변'},
 {'place': 'mala_strana', 'src': '/static/journal/media/0072e32d6c5e.jpg', 'cap': 'Day4 · 말라스트라나'},
 {'place': 'mala_strana', 'src': '/static/journal/media/56a3cc962d77.jpg', 'cap': 'Day4 · 말라스트라나'},
 {'place': 'mala_strana', 'src': '/static/journal/media/cfb38896d1f0.jpg', 'cap': 'Day4 · 말라스트라나'},
 {'place': 'mala_strana', 'src': '/static/journal/media/5b120359c9a2.jpg', 'cap': 'Day4 · 말라스트라나'},
 {'place': 'mala_strana', 'src': '/static/journal/media/7b9ad2bbaa81.jpg', 'cap': 'Day4 · 말라스트라나'},
 {'place': 'dresden', 'src': '/static/journal/media/8366c833b03d.jpg', 'cap': 'Day6 · 드레스덴'},
 {'place': 'dresden', 'src': '/static/journal/media/fa7ebbb435e9.jpg', 'cap': 'Day6 · 드레스덴'},
 {'place': 'dresden', 'src': '/static/journal/media/f675a0c379fa.jpg', 'cap': 'Day6 · 드레스덴'},
 {'place': 'dresden', 'src': '/static/journal/media/3941c15711a2.jpg', 'cap': 'Day6 · 드레스덴'},
 {'place': 'dresden', 'src': '/static/journal/media/9b78ff55ae5f.jpg', 'cap': 'Day6 · 드레스덴'},
 {'place': 'krumlov', 'src': '/static/journal/media/a8eebbb5eca8.jpg', 'cap': 'Day7 · 체스키 크룸로프'},
 {'place': 'krumlov', 'src': '/static/journal/media/3966e08478cc.jpg', 'cap': 'Day7 · 체스키 크룸로프'},
 {'place': 'krumlov', 'src': '/static/journal/media/dab5f8928492.jpg', 'cap': 'Day7 · 체스키 크룸로프'},
 {'place': 'krumlov', 'src': '/static/journal/media/7affb09c7040.jpg', 'cap': 'Day7 · 체스키 크룸로프'},
 {'place': 'krumlov', 'src': '/static/journal/media/56f8c8e19cb9.jpg', 'cap': 'Day8 · 체스키 크룸로프'},
 {'place': 'hluboka', 'src': '/static/journal/media/c648f5dc899f.jpg', 'cap': 'Day8 · 흘루보카 성'},
 {'place': 'hluboka', 'src': '/static/journal/media/1ff05a72d5c3.jpg', 'cap': 'Day8 · 흘루보카 성'},
 {'place': 'hluboka', 'src': '/static/journal/media/01afd6ab1ac5.jpg', 'cap': 'Day8 · 흘루보카 성'},
 {'place': 'hluboka', 'src': '/static/journal/media/80952f6a1056.jpg', 'cap': 'Day8 · 흘루보카 성'},
 {'place': 'hluboka', 'src': '/static/journal/media/5b6a2b78eb8b.jpg', 'cap': 'Day8 · 흘루보카 성'},
 {'place': 'vinohrady', 'src': '/static/journal/media/f1e5af407e3f.jpg', 'cap': 'Day8 · 비노흐라디'},
 {'place': 'vinohrady', 'src': '/static/journal/media/26786ca8e8cd.jpg', 'cap': 'Day10 · 비노흐라디'},
 {'place': 'vinohrady', 'src': '/static/journal/media/aab21b032380.jpg', 'cap': 'Day10 · 비노흐라디'},
 {'place': 'vinohrady', 'src': '/static/journal/media/774f772b03ad.jpg', 'cap': 'Day10 · 비노흐라디'},
 {'place': 'vinohrady', 'src': '/static/journal/media/389e20c3d736.jpg', 'cap': 'Day10 · 비노흐라디'},
 {'place': 'vinohrady', 'src': '/static/journal/media/020b5a1557e5.jpg', 'cap': 'Day10 · 비노흐라디'},
 {'place': 'museum', 'src': '/static/journal/media/3688ae392707.jpg', 'cap': 'Day9 · 국립 박물관'},
 {'place': 'museum', 'src': '/static/journal/media/d3b49bfdace4.jpg', 'cap': 'Day9 · 국립 박물관'},
 {'place': 'museum', 'src': '/static/journal/media/6ec73dad64cb.jpg', 'cap': 'Day9 · 국립 박물관'},
 {'place': 'museum', 'src': '/static/journal/media/9e10362f9204.jpg', 'cap': 'Day9 · 국립 박물관'},
 {'place': 'museum', 'src': '/static/journal/media/e6f78741d4e8.jpg', 'cap': 'Day9 · 국립 박물관'},
 {'place': 'riegrovy', 'src': '/static/journal/media/f5f32e46dd94.jpg', 'cap': 'Day10 · 리흐로비 공원'},
 {'place': 'riegrovy', 'src': '/static/journal/media/4c0c57d7034d.jpg', 'cap': 'Day10 · 리흐로비 공원'},
 {'place': 'riegrovy', 'src': '/static/journal/media/964ec4eb775d.jpg', 'cap': 'Day9 · 리흐로비 공원'},
 {'place': 'riegrovy', 'src': '/static/journal/media/153b9f5fe5ce.jpg', 'cap': 'Day9 · 리흐로비 공원'},
 {'place': 'riegrovy', 'src': '/static/journal/media/12910974defa.jpg', 'cap': 'Day9 · 리흐로비 공원'},
 {'place': 'airport', 'src': '/static/journal/media/74b2959978d2.jpg', 'cap': 'Day10 · 공항'},
 {'place': 'airport', 'src': '/static/journal/media/6e9a54a2839c.jpg', 'cap': 'Day10 · 공항'},
 {'place': 'airport', 'src': '/static/journal/media/00c262838702.jpg', 'cap': 'Day10 · 공항'},
 {'place': 'airport', 'src': '/static/journal/media/a863dc95756b.jpg', 'cap': 'Day10 · 공항'},
 {'place': 'airport', 'src': '/static/journal/media/a20043f80660.jpg', 'cap': 'Day10 · 공항'}]

GALLERY = {'d1_s1': ['/static/journal/media/efe224e3f42d.jpg',
           '/static/journal/media/ae2ffea2522d.jpg',
           '/static/journal/media/8552c5642fa8.jpg',
           '/static/journal/media/f8ad1e42f5e9.jpg',
           '/static/journal/media/03f89ce02198.jpg',
           '/static/journal/media/290a97f7f11a.jpg',
           '/static/journal/media/6e30e645d16f.jpg',
           '/static/journal/media/4b8c82be0c5c.jpg',
           '/static/journal/media/4bba77d6716e.jpg',
           '/static/journal/media/538dfa73595d.jpg',
           '/static/journal/media/9bb0b96601dc.jpg',
           '/static/journal/media/03cc93921971.jpg'],
 'd1_s2': ['/static/journal/media/9e20a0d45657.jpg',
           '/static/journal/media/9a2c86586f9d.jpg',
           '/static/journal/media/2320a103d8a5.jpg',
           '/static/journal/media/01c2a65c3164.jpg',
           '/static/journal/media/b93d55c4bb04.jpg',
           '/static/journal/media/6a1fc824d991.jpg',
           '/static/journal/media/5531af80617d.jpg',
           '/static/journal/media/89f4773a435c.jpg',
           '/static/journal/media/b0941db7f1c9.jpg',
           '/static/journal/media/e3b2e1d96bab.jpg',
           '/static/journal/media/418e030ac3b0.jpg',
           '/static/journal/media/c194eec49ca3.jpg'],
 'd1_s3': ['/static/journal/media/bd570ee7cc11.jpg',
           '/static/journal/media/38f8dc307655.jpg',
           '/static/journal/media/ed11e1ca1385.jpg',
           '/static/journal/media/81aa71e755b7.jpg',
           '/static/journal/media/fcba30609829.jpg',
           '/static/journal/media/3efba5599bf6.jpg',
           '/static/journal/media/4a7c77e0c514.jpg',
           '/static/journal/media/1d8f69ddf87c.jpg',
           '/static/journal/media/486033c98f46.jpg',
           '/static/journal/media/00e7eb04e206.jpg',
           '/static/journal/media/06eceb027c54.jpg',
           '/static/journal/media/676893b6a0f9.jpg'],
 'd2_s1': ['/static/journal/media/417af56caaf0.jpg',
           '/static/journal/media/f8e030e20de3.jpg',
           '/static/journal/media/3155267eb2f0.jpg',
           '/static/journal/media/20a4f1caed0e.jpg',
           '/static/journal/media/e1761c20c74c.jpg',
           '/static/journal/media/fb46134a6c8c.jpg',
           '/static/journal/media/68b12d1fdf16.jpg',
           '/static/journal/media/e7e6aaeaaca3.jpg',
           '/static/journal/media/14af50943e6a.jpg',
           '/static/journal/media/b517a9a973ac.jpg',
           '/static/journal/media/61b4c37d1e49.jpg',
           '/static/journal/media/c0beef7f2ebe.jpg'],
 'd2_s2': ['/static/journal/media/87bc692cc8cd.jpg',
           '/static/journal/media/a9aa1293b50b.jpg',
           '/static/journal/media/a52ac28331f3.jpg',
           '/static/journal/media/bbe5b7bacdae.jpg',
           '/static/journal/media/0dc70b69c8ce.jpg',
           '/static/journal/media/64e7ca5dbc14.jpg',
           '/static/journal/media/79b5a0bfdab8.jpg',
           '/static/journal/media/4050fa389e8c.jpg',
           '/static/journal/media/dfa4d7aef041.jpg',
           '/static/journal/media/5c01ace476a6.jpg',
           '/static/journal/media/b9bd81202997.jpg',
           '/static/journal/media/37a08fa54d23.jpg'],
 'd2_s3': ['/static/journal/media/f90c8b366d52.jpg',
           '/static/journal/media/17961092a2f7.jpg',
           '/static/journal/media/491cfbb61edf.jpg',
           '/static/journal/media/3164da96b291.jpg',
           '/static/journal/media/e38ceef92192.jpg',
           '/static/journal/media/a50d28fedd05.jpg'],
 'd3_s1': ['/static/journal/media/6f8740305653.jpg',
           '/static/journal/media/38735aed7cff.jpg',
           '/static/journal/media/d8c97c153f0f.jpg',
           '/static/journal/media/8239bcfb5938.jpg',
           '/static/journal/media/e58e3c821dc7.jpg',
           '/static/journal/media/536b6f29de3c.jpg',
           '/static/journal/media/4d923f5d056d.jpg',
           '/static/journal/media/25e1f1a4a9ef.jpg',
           '/static/journal/media/a15e67c3d64a.jpg',
           '/static/journal/media/4dc4165de963.jpg',
           '/static/journal/media/6d7a2062ddaf.jpg',
           '/static/journal/media/1ab0d24e8300.jpg'],
 'd3_s2': ['/static/journal/media/67711413e70e.jpg',
           '/static/journal/media/1e626e37d410.jpg',
           '/static/journal/media/822d4f3740d3.jpg',
           '/static/journal/media/a8ad94afef2b.jpg',
           '/static/journal/media/cb479b09b643.jpg',
           '/static/journal/media/1fbfe65f3d58.jpg',
           '/static/journal/media/f3ef00ec3b5b.jpg',
           '/static/journal/media/c93fe6d2b85e.jpg',
           '/static/journal/media/909d4c59196f.jpg',
           '/static/journal/media/e22658fcd2e5.jpg',
           '/static/journal/media/e956f4d96eaf.jpg',
           '/static/journal/media/5ec235942eb2.jpg'],
 'd3_s3': ['/static/journal/media/d3afb80723b0.jpg',
           '/static/journal/media/711a545ee27c.jpg',
           '/static/journal/media/8468ec7686cd.jpg',
           '/static/journal/media/00da1a5dcff3.jpg',
           '/static/journal/media/352cc4593b7e.jpg',
           '/static/journal/media/c0a964700046.jpg',
           '/static/journal/media/1fe1946870bb.jpg',
           '/static/journal/media/616d79104818.jpg',
           '/static/journal/media/8a196a6433ac.jpg',
           '/static/journal/media/530cc33dac1c.jpg',
           '/static/journal/media/8d3db0c4aed8.jpg',
           '/static/journal/media/89c01ccd3e6f.jpg'],
 'd4_s1': ['/static/journal/media/9362a3f7f59a.jpg',
           '/static/journal/media/06fd516f8605.jpg',
           '/static/journal/media/8964af4ad4af.jpg',
           '/static/journal/media/7881124a6a2b.jpg',
           '/static/journal/media/750d1174bf8e.jpg',
           '/static/journal/media/da2c3208e4de.jpg',
           '/static/journal/media/43cf65fab557.jpg',
           '/static/journal/media/b6a9abb42b20.jpg',
           '/static/journal/media/e7cf225ca42f.jpg',
           '/static/journal/media/d3c364533b57.jpg',
           '/static/journal/media/a1372b020187.jpg',
           '/static/journal/media/0ed7a18d0a6e.jpg'],
 'd4_s2': ['/static/journal/media/25ae0448befe.jpg',
           '/static/journal/media/8cdeefb6369b.jpg',
           '/static/journal/media/06af201d0b3f.jpg',
           '/static/journal/media/930d3322c740.jpg',
           '/static/journal/media/f417895f2d47.jpg',
           '/static/journal/media/df0d97a7e1ad.jpg',
           '/static/journal/media/b4c55db45a23.jpg',
           '/static/journal/media/b37a904ce220.jpg',
           '/static/journal/media/7097149e0009.jpg',
           '/static/journal/media/600ed56dab3b.jpg',
           '/static/journal/media/b66c3113d33c.jpg',
           '/static/journal/media/d64dab1bcb18.jpg'],
 'd4_s3': ['/static/journal/media/5636f80d4ac4.jpg',
           '/static/journal/media/1ef36bdf8d95.jpg',
           '/static/journal/media/7e290a10d1ba.jpg',
           '/static/journal/media/401094e5346c.jpg',
           '/static/journal/media/00aba5a79aee.jpg',
           '/static/journal/media/f3f67e953543.jpg',
           '/static/journal/media/bfc74714c4d3.jpg',
           '/static/journal/media/4bc25cb20b34.jpg',
           '/static/journal/media/4637663ea2b1.jpg',
           '/static/journal/media/330bda98b2b0.jpg',
           '/static/journal/media/87fbd5c32e07.jpg',
           '/static/journal/media/45bfd010628e.jpg'],
 'd4_s4': ['/static/journal/media/e1b0de3eaf7b.jpg',
           '/static/journal/media/04ab9adb9260.jpg',
           '/static/journal/media/3a04bc652f12.jpg',
           '/static/journal/media/4eacf5094157.jpg',
           '/static/journal/media/3d761b335836.jpg',
           '/static/journal/media/8bac834a44f9.jpg'],
 'd5_s1': ['/static/journal/media/3e8d901d5114.jpg',
           '/static/journal/media/20e3d7506f55.jpg',
           '/static/journal/media/10038c0c06c6.jpg',
           '/static/journal/media/33cfa5e29ce4.jpg',
           '/static/journal/media/ffe843d1f6c1.jpg',
           '/static/journal/media/ed7a5fc2fb12.jpg',
           '/static/journal/media/ed4088c1e523.jpg',
           '/static/journal/media/d9b459ae84bd.jpg',
           '/static/journal/media/5192ee225d6c.jpg',
           '/static/journal/media/dd47989092ae.jpg',
           '/static/journal/media/4c50c45ee807.jpg',
           '/static/journal/media/b79d77a20115.jpg'],
 'd5_s2': ['/static/journal/media/5bf4d413e1a5.jpg',
           '/static/journal/media/19e727b556b5.jpg',
           '/static/journal/media/bd49e49d0f9c.jpg',
           '/static/journal/media/1bb6487767eb.jpg',
           '/static/journal/media/3c56f3bcbe26.jpg',
           '/static/journal/media/b0e61de6b36f.jpg',
           '/static/journal/media/359dab0ad0f3.jpg',
           '/static/journal/media/af00e87c1dcb.jpg',
           '/static/journal/media/d3bd7218179a.jpg',
           '/static/journal/media/6746f2394d50.jpg',
           '/static/journal/media/3ba4005c19b6.jpg',
           '/static/journal/media/0830d50cd5a1.jpg'],
 'd5_s3': ['/static/journal/media/e9c05083fb81.jpg',
           '/static/journal/media/ed580dfc5ecc.jpg',
           '/static/journal/media/1ea8d6a6cd11.jpg',
           '/static/journal/media/b16048da0aa5.jpg',
           '/static/journal/media/82a678cd1265.jpg',
           '/static/journal/media/0db00bd8872b.jpg',
           '/static/journal/media/74d14e7db373.jpg',
           '/static/journal/media/67a3b2359f7b.jpg',
           '/static/journal/media/b6e5c46c765e.jpg',
           '/static/journal/media/62f360f10141.jpg',
           '/static/journal/media/8750bb719664.jpg',
           '/static/journal/media/00262ad8796b.jpg'],
 'd6_s1': ['/static/journal/media/8b88c67b41b5.jpg',
           '/static/journal/media/201a0d8bc8fc.jpg',
           '/static/journal/media/6214857f2447.jpg',
           '/static/journal/media/4dc7a487e8a7.jpg',
           '/static/journal/media/b802d90f15d7.jpg',
           '/static/journal/media/3b9c4f74981c.jpg',
           '/static/journal/media/387a6f1c13e0.jpg',
           '/static/journal/media/996e09caae38.jpg',
           '/static/journal/media/8a5232ac5546.jpg',
           '/static/journal/media/03071d10461d.jpg',
           '/static/journal/media/b7cbe9f6590b.jpg',
           '/static/journal/media/d3297ac6e0b5.jpg'],
 'd6_s2': ['/static/journal/media/27ab99664ac4.jpg',
           '/static/journal/media/2dff82a6c556.jpg',
           '/static/journal/media/8e59eebefb6e.jpg',
           '/static/journal/media/e6b342f2373a.jpg',
           '/static/journal/media/e44538ef2c9a.jpg',
           '/static/journal/media/60eb693be1a9.jpg',
           '/static/journal/media/de9915a01898.jpg',
           '/static/journal/media/7390f52a6a3c.jpg',
           '/static/journal/media/e4a94fa223d1.jpg',
           '/static/journal/media/5a19fefccaf2.jpg',
           '/static/journal/media/c7dd595ecbcc.jpg',
           '/static/journal/media/a40de162ea7a.jpg'],
 'd6_s3': ['/static/journal/media/d05952bb4543.jpg',
           '/static/journal/media/94b040851c7f.jpg',
           '/static/journal/media/90f8a2719b8e.jpg',
           '/static/journal/media/712e014525ea.jpg',
           '/static/journal/media/191b4403bbf2.jpg',
           '/static/journal/media/05ced86d5d79.jpg',
           '/static/journal/media/ac559b78cb91.jpg',
           '/static/journal/media/878aa53b0c1c.jpg',
           '/static/journal/media/3ec8ccbfb0b2.jpg',
           '/static/journal/media/e197f4105d1d.jpg',
           '/static/journal/media/ae8c3c1566f7.jpg',
           '/static/journal/media/175f14b0a275.jpg'],
 'd7_s1': ['/static/journal/media/dc041205f265.jpg',
           '/static/journal/media/681d9ed6b4e9.jpg',
           '/static/journal/media/df5c7f738e0a.jpg',
           '/static/journal/media/c1993fab7d2f.jpg',
           '/static/journal/media/8d8685c8e1eb.jpg',
           '/static/journal/media/05d37507f30e.jpg',
           '/static/journal/media/f1b04096a527.jpg',
           '/static/journal/media/e589b05afd0b.jpg',
           '/static/journal/media/caf263db63ac.jpg',
           '/static/journal/media/5add8b9fe119.jpg',
           '/static/journal/media/53cebe4ca232.jpg',
           '/static/journal/media/21a889bd2141.jpg'],
 'd7_s2': ['/static/journal/media/09c4e71ce92f.jpg',
           '/static/journal/media/1920a4a6da14.jpg',
           '/static/journal/media/b11abbca72c2.jpg',
           '/static/journal/media/8f302276fccf.jpg',
           '/static/journal/media/46e2f7d621cb.jpg',
           '/static/journal/media/366136714341.jpg',
           '/static/journal/media/fe091d586473.jpg',
           '/static/journal/media/af13ba84a0ba.jpg',
           '/static/journal/media/ece5979e6b7d.jpg',
           '/static/journal/media/65c6a086640b.jpg',
           '/static/journal/media/b5d4c19c9475.jpg',
           '/static/journal/media/73f3436ede61.jpg'],
 'd7_s3': ['/static/journal/media/ce90f2138f8a.jpg',
           '/static/journal/media/b621a7d5a758.jpg',
           '/static/journal/media/0700aa332c82.jpg',
           '/static/journal/media/98fd1c457424.jpg',
           '/static/journal/media/2599f9013348.jpg',
           '/static/journal/media/b8600393ee5a.jpg',
           '/static/journal/media/f2988c2c5de6.jpg',
           '/static/journal/media/ec209d0191fe.jpg',
           '/static/journal/media/3ffe470ff967.jpg',
           '/static/journal/media/f9eab5201eca.jpg',
           '/static/journal/media/5ff47a9a600f.jpg',
           '/static/journal/media/619324f8d864.jpg'],
 'd8_s1': ['/static/journal/media/ce5b8c196b0a.jpg',
           '/static/journal/media/17365e729dd7.jpg',
           '/static/journal/media/65c9ceb1958d.jpg',
           '/static/journal/media/9cfc42c29af6.jpg',
           '/static/journal/media/be4f8e9cc3c0.jpg',
           '/static/journal/media/2912ab452396.jpg',
           '/static/journal/media/05d52c13ea14.jpg',
           '/static/journal/media/d186f49369ae.jpg',
           '/static/journal/media/12e8e5d21777.jpg',
           '/static/journal/media/b0f6af12be45.jpg',
           '/static/journal/media/52af33bfc8ca.jpg',
           '/static/journal/media/4babe461c229.jpg'],
 'd8_s2': ['/static/journal/media/9d65f58ffa69.jpg',
           '/static/journal/media/90e3322b8cb5.jpg',
           '/static/journal/media/ccda3d0f366e.jpg',
           '/static/journal/media/fd975a516036.jpg',
           '/static/journal/media/7f95e9a94afb.jpg',
           '/static/journal/media/0e7ee1dbde0d.jpg',
           '/static/journal/media/800ca173c974.jpg',
           '/static/journal/media/dc716bc00790.jpg',
           '/static/journal/media/998a54aa0993.jpg',
           '/static/journal/media/cd1ac3fb8379.jpg',
           '/static/journal/media/61e9b75d4800.jpg',
           '/static/journal/media/3ee691de22ce.jpg'],
 'd8_s3': ['/static/journal/media/47260e9e09af.jpg',
           '/static/journal/media/cf633c81c812.jpg',
           '/static/journal/media/1efb946e4b81.jpg',
           '/static/journal/media/a067636a677d.jpg',
           '/static/journal/media/bcd5a3450543.jpg',
           '/static/journal/media/a20b4884c83b.jpg'],
 'd9_s1': ['/static/journal/media/c5469c53596a.jpg',
           '/static/journal/media/705a2d60d1ec.jpg',
           '/static/journal/media/45a6d4a15dcb.jpg',
           '/static/journal/media/5b155523ec9b.jpg',
           '/static/journal/media/e8a17e490784.jpg',
           '/static/journal/media/42e6f30834a9.jpg',
           '/static/journal/media/c0ccbb6eda58.jpg',
           '/static/journal/media/83a545d25f31.jpg',
           '/static/journal/media/aebb4cc7e4a8.jpg',
           '/static/journal/media/dcc49eda9c40.jpg',
           '/static/journal/media/62e885852aee.jpg',
           '/static/journal/media/fdde065e7727.jpg'],
 'd9_s2': ['/static/journal/media/2930b2533f8f.jpg',
           '/static/journal/media/1062e2bbc74f.jpg',
           '/static/journal/media/513dc682d642.jpg',
           '/static/journal/media/37db7eb86ed3.jpg',
           '/static/journal/media/a3cc226481fe.jpg',
           '/static/journal/media/47665cce675f.jpg',
           '/static/journal/media/7be49de050b9.jpg',
           '/static/journal/media/fee1685606d9.jpg',
           '/static/journal/media/9b8fe0c6f94d.jpg',
           '/static/journal/media/279e47e7077d.jpg',
           '/static/journal/media/57d069e88bb4.jpg',
           '/static/journal/media/0065f70eb125.jpg'],
 'd10_s1': ['/static/journal/media/b1a9554f22c5.jpg',
            '/static/journal/media/2ee133b7fb32.jpg',
            '/static/journal/media/9c0ce48443b3.jpg',
            '/static/journal/media/f91c9c2a67f9.jpg',
            '/static/journal/media/661f7095d730.jpg',
            '/static/journal/media/f4e7c0a1c2bb.jpg',
            '/static/journal/media/26648de0079f.jpg',
            '/static/journal/media/237f97ef6268.jpg',
            '/static/journal/media/0ecbb8590fd5.jpg',
            '/static/journal/media/ffb7b521d49c.jpg',
            '/static/journal/media/20434622c20b.jpg',
            '/static/journal/media/7a86ba22769c.jpg'],
 'd10_s2': ['/static/journal/media/d4ef2094213b.jpg',
            '/static/journal/media/f2ffa663de80.jpg',
            '/static/journal/media/bbf975b7608a.jpg',
            '/static/journal/media/e77a1bd8ad9e.jpg',
            '/static/journal/media/60fa15f6e4e6.jpg',
            '/static/journal/media/84eaee3a6373.jpg',
            '/static/journal/media/df4b52187c42.jpg',
            '/static/journal/media/1e57129309ae.jpg',
            '/static/journal/media/4b54ca87c330.jpg',
            '/static/journal/media/b7a94177aab0.jpg',
            '/static/journal/media/349c14bafa91.jpg',
            '/static/journal/media/dc462777abbb.jpg']}

